api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "payment-hide-cod"
type = "function"
uid = "34c66544-fa15-2335-6acd-423ddf501c2acf81bf63"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.payment-methods.transform.run"
  input_query = "src/cart_payment_methods_transform_run.graphql"
  export = "cart-payment-methods-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
