api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "shipping-free-threshold"
type = "function"
uid = "1ee43ab5-3b46-048e-e300-a8422f7739f2bd73f724"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart-delivery-options-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
